# Generated by Django 4.2.7 on 2025-10-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('HOT', 'Hot Lead'), ('WARM', 'Warm Lead'), ('COLD', 'Cold Lead'), ('CONVERTED', 'Converted'), ('CONSULTATION', 'Consultation Only'), ('FOLLOW_UP', 'Follow-up Required')], default='WARM', max_length=20)),
                ('case_type', models.CharField(blank=True, choices=[('DUI', 'DUI/Drunk Driving'), ('SPEEDING', 'Speeding Violation'), ('LICENSE_SUSPENSION', 'License Suspension'), ('ACCIDENT', 'Traffic Accident'), ('PARKING', 'Parking Violation'), ('OTHER', 'Other Traffic Violation'), ('CRIMINAL', 'Criminal Case (264.1 УК РФ)')], max_length=20, null=True)),
                ('region', models.CharField(choices=[('MOSCOW', 'Moscow'), ('REGIONS', 'Other Regions')], default='REGIONS', max_length=20)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi_calculation', models.TextField(blank=True, null=True)),
                ('win_probability', models.IntegerField(blank=True, help_text='Percentage chance of winning', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='leads.lead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
