# Generated by Django 4.2.7 on 2025-10-13 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('protocol', 'Протокол об административном правонарушении'), ('photo', 'Фотоматериалы'), ('video', 'Видеозапись'), ('court_decision', 'Решение суда'), ('medical_certificate', 'Медицинская справка'), ('witness_statement', 'Показания свидетелей'), ('other', 'Другое')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='leads.lead')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
