# Generated by Django 4.2.7 on 2025-10-10 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('SMS_SENT', 'SMS Code Sent'), ('SIGNED', 'Signed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('client_data', models.JSONField(default=dict)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='contracts/generated/')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('code_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('verification_code', models.CharField(max_length=6)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_verifications', to='contract_manager.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('case_type', models.CharField(max_length=20)),
                ('instance', models.CharField(choices=[('1', '1st Instance'), ('2', '2nd Instance'), ('3', '3rd Instance'), ('4', '4th Instance')], max_length=1)),
                ('representation_type', models.CharField(choices=[('WITHOUT_POA', 'Without Power of Attorney'), ('WITH_POA', 'With Power of Attorney'), ('NO_REPRESENTATION', 'Without Representation'), ('WITH_REPRESENTATION', 'With Court Representation')], max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('template_file', models.CharField(max_length=500)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('success_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('required_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('case_type', 'instance', 'representation_type', 'region')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.contracttemplate'),
        ),
    ]
