# Generated by Django 4.2.7 on 2025-10-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='case_description',
            field=models.TextField(blank=True, help_text='Description of legal services to be provided', null=True),
        ),
    ]
